spring:
  config:
    import: application-secret.yml
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: postgres
  web:
    resources:
      static-locations: classpath:/static/
  data:
    redis:
      host: localhost     # test redis (need another docker container)
      port: 6379


server:
  port: 8080
  address: 0.0.0.0



nbu:
  api:
    url: https://bank.gov.ua/NBUStatService/v1/statdirectory/exchange?json





