spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://dpg-ctg75gbgbbvc73au8r00-a.oregon-postgres.render.com/storagebox
    username: storagebox_user
    password: vrSanpxy7Z1aUfKWfygaQ9hsojDT3m5i
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      platform: postgres
  web:
    resources:
      static-locations: classpath:/static/

server:
  port: 8080

admin:
  login: admin@example.com
  password: admin


#    url: jdbc:postgresql://localhost:5432/storagebox
#    username: postgres
#    password: postgres