spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/storagebox
    username: postgres
    password: postgres
  sql:
    init:
      platform: postgres
  web:
    resources:
      static-locations: classpath:/static/