spring:
  config:
    import: application-secret.yml
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: postgres
  web:
    resources:
      static-locations: classpath:/static/

server:
  port: 8080


nbu:
  api:
    url: https://bank.gov.ua/NBUStatService/v1/statdirectory/exchange?json



#  redis:
#    host: localhost
#    port: 6379
#
#  jackson:
#    serialization:
#      write-dates-as-timestamps=false

#    url: jdbc:postgresql://localhost:5432/storagebox
#    username: postgres
#    password: postgres